spring:
  datasource:
    url: jdbc:postgresql://pgmaster:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics  # Включение нужных endpoint'ов
      base-path: /actuator  # Базовый путь для Actuator (по умолчанию /actuator)
  metrics:
    tags:
      application: my-app  # Добавление тегов к метрикам
  endpoint:
    prometheus:
      enabled: true  # Явное включение endpoint'а Prometheus
logging:
  config: classpath:logback.xml
